In [1]:
import numpy as np


A scalar is a single numerical value.

In [7]:
# 1 Scalar

scalar= np.array(5)
print(f"Scalar : {scalar}")
print(f'shape of the scalar : {scalar.shape}')
print(f'Dimention of the scalar : {scalar.ndim} ')

Scalar : 5
shape of the scalar : ()
Dimention of the scalar : 0 


A vector is a one-dimensional array. Here, the first row of the image is represented as a vector

In [6]:
#Vector :
vector1 = np.array([8,6,7,9])
print(f"Vector : {vector1}")
print(f'shape of the vector : {vector1.shape}')
print(f'Dimention of the vector : {vector1.ndim} ')

Vector : [8 6 7 9]
shape of the vector : (4,)
Dimention of the vector : 1 


A matrix is a two-dimensional array consisting of rows and columns.

In [12]:
matrix1 = np.array([[123,432,443],[321,345,897]])
print(f"Matrix : \n{matrix1}")
print(f'shape of the matrix :{matrix1.shape}')
print(f'Dimention of the matrix : {matrix1.ndim} ')

Matrix : 
[[123 432 443]
 [321 345 897]]
shape of the matrix :(2, 3)
Dimention of the matrix : 2 


A tensor is a multi-dimensional array with three or more dimensions.

In [14]:
tensor = np.array([[[12,34,66],[34,63,67],
                    [53,52,75],[43,64,77]]])
print(f"Tensor : \n{tensor}")
print(f'shape of the tensor :{tensor.shape}')
print(f'Dimention of the tensor : {tensor.ndim} ')

Tensor : 
[[[12 34 66]
  [34 63 67]
  [53 52 75]
  [43 64 77]]]
shape of the tensor :(1, 4, 3)
Dimention of the tensor : 3 


### Difference Between (n,) and (n,1)

-(n,) represents a one-dimensional vector with a single axis.

-(n,1) represents a two-dimensional column vector with one column.

In [18]:
# Apply element-wise operations

scores = np.array([
                  [80, 90, 85],
                  [70, 75, 78],
                  [95, 88, 92],
                  [60, 65, 70]])

extra_credit = np.array([[2, 1, 3],
                         [1, 2, 1],
                         [3, 2, 2],
                         [1, 1, 1]])

print(f'Scores Data : \n{scores}')
print('-'*40)
print(f'Extra Credit : \n{extra_credit}')
print('-'*40)
print(f'Addition :\n {scores + extra_credit}')
print('-'*40)
print(f'Subtraction :\n {scores - extra_credit}')
print('-'*40)
print(f'Multiplication :\n {scores * extra_credit}')
print('-'*40)
print(f'Division :\n {scores / extra_credit}')

Scores Data : 
[[80 90 85]
 [70 75 78]
 [95 88 92]
 [60 65 70]]
----------------------------------------
Extra Credit : 
[[2 1 3]
 [1 2 1]
 [3 2 2]
 [1 1 1]]
----------------------------------------
Addition :
 [[82 91 88]
 [71 77 79]
 [98 90 94]
 [61 66 71]]
----------------------------------------
Subtraction :
 [[78 89 82]
 [69 73 77]
 [92 86 90]
 [59 64 69]]
----------------------------------------
Multiplication :
 [[160  90 255]
 [ 70 150  78]
 [285 176 184]
 [ 60  65  70]]
----------------------------------------
Division :
 [[40.         90.         28.33333333]
 [70.         37.5        78.        ]
 [31.66666667 44.         46.        ]
 [60.         65.         70.        ]]


In [22]:
# Apply aggregations:
print(f'Sum of Scores : {scores.sum()}')
print(f'Mean of Scores : {scores.mean()}')
print(f'Max of Scores : {scores.max()}')
print(f'Min of Scores : {scores.min()}')
print(f'Standard Deviation of Scores : {scores.std()}')

print('-'*40)

print(f'Sum of Extra Credit : {extra_credit.sum()}')
print(f'Mean of Extra Credit : {extra_credit.mean()}')
print(f'Max of Extra Credit : {extra_credit.max()}')
print(f'Min of Extra Credit : {extra_credit.min()}')
print(f'Standard Deviation of Extra Credit : {extra_credit.std()}')

Sum of Scores : 948
Mean of Scores : 79.0
Max of Scores : 95
Min of Scores : 60
Standard Deviation of Scores : 10.801234497346433
----------------------------------------
Sum of Extra Credit : 20
Mean of Extra Credit : 1.6666666666666667
Max of Extra Credit : 3
Min of Extra Credit : 1
Standard Deviation of Extra Credit : 0.7453559924999299


In [28]:
# 1. Create two vectors v and w.
v= np.array([12.50, 11.99, 13.00])
w=np.array([45.00, 42.50, 46.99])
print(f'victor v : {v}')
print(f'victor w : {w}')
print('-'*40)
# Vector addition
print(f'Victor Addition : {v+w}' )
print('-'*40)
# Vector subtraction
print(f'Victor Subtraction : {v-w}' )
print('-'*40)
# Scalar multiplication
scalar1=np.array(5)
print(f'Scalar multiplication :{v*scalar1} ')
print('-'*40)
# Dot product
print(f'Dot product : {np.dot(v,w)}')
print('-'*40)
# Norm
norm_v = np.linalg.norm(v)
norm_w = np.linalg.norm(w)
print("||v|| =", norm_v)
print()
print("||w|| =", norm_w)

victor v : [12.5  11.99 13.  ]
victor w : [45.   42.5  46.99]
----------------------------------------
Victor Addition : [57.5  54.49 59.99]
----------------------------------------
Victor Subtraction : [-32.5  -30.51 -33.99]
----------------------------------------
Scalar multiplication :[62.5  59.95 65.  ] 
----------------------------------------
Dot product : 1682.9450000000002
----------------------------------------
||v|| = 21.656641013786047

||w|| = 77.71299826927282


In [ ]:
# 3. Create row vector and column vector.

col_vect = np.array([[1],[2] ,[3],[4]])
row_vect = np.array([[1, 2, 3 ,4]])
print(f'row vector : {row_vect}')
print()
print(f'column vector :\n {col_vect}')



the dot porduct measures the alignment of the vectors

- if the result is large positive means the vectors are in the same directions

- if the result is near zero means the vectors are orthogonal

- if the result is negative the vectors are in opposit diractions

In [38]:
# 5.Create two vectors and test
v1 = np.array([1,2])
v2 = np.array([3,4])
print(f'v1 : {v1} \nv2 : {v2}')
print()
A= np.column_stack([v1,v2])
print(f"Rank([v1, v2]) = {np.linalg.matrix_rank(A)} ")
print()

# Are they linearly independent?
print('The vectors are linearly independent.')

# Do they form a basis for R2? yes the rank is 2
print("The vectors form a basis for R².")

v1 : [1 2] 
v2 : [3 4]

Rank([v1, v2]) = 2 

The vectors are linearly independent.
The vectors form a basis for R².


In [39]:
# Create a linear combination:
# a * v + b * w
a=2
b=3

lin_comp = a*v1 + b*v2
print(f'linear combination : {lin_comp}')

linear combination : [11 16]


In [45]:
# Apply a linear transformation using a matrix:
# Scaling
scale_mat = np.array([[2,4],[6,3]])
scale_vec = scale_mat.dot(v1)
print(f'Original matrix : \n{scale_mat}')
print()
print(f'Scaled : {scale_vec}')
print()
# o Rotation
rotation = np.array([[0,-1],
                      [1,0]])
rotated_vector = rotation @ v1

print(f'Original matrix : \n{rotation}')
print()
print("Rotated Vector:", rotated_vector)


Original matrix : 
[[2 4]
 [6 3]]

Scaled : [10 12]

Original matrix : 
[[ 0 -1]
 [ 1  0]]

Rotated Vector: [-2  1]


**Why are vectors, matrices, and transformations important in Machine Learning?**

-Because data is represented as vectors, datasets are stored as matrices, and transformations are used to convert data into forms that help models learn