In [21]:
import numpy as np

In [22]:
A = np.array([[1, 3],
              [2, 4]])

B = np.array([[2, 0],
              [1, 2]])

*   Compute A + B
* Compute A @ B
* Compute B @ A
* Are A @ B and B @ A equal?




In [23]:
print(f'A+B =\n {A+B}')
print()
print(f'A@B =\n {A@B}')
print()
print(f'B@A =\n {B@A}')
print()
print('A @ B dont equal B @ A ')

A+B =
 [[3 3]
 [3 6]]

A@B =
 [[5 6]
 [8 8]]

B@A =
 [[ 2  6]
 [ 5 11]]

A @ B dont equal B @ A 


#Determinant & Inverse

1.   Compute determinant of A
2. Compute inverse of A
3. Verify A @ A⁻¹ = I




In [24]:
det_A = np.linalg.det(A)
print(f'Determinant of A = {det_A}')
print()

inv_A= np.linalg.inv(A)
print(f"inversive of A :\n {inv_A}")
print()

print(f' A @ A⁻¹ = I  \n {A@inv_A}' )

Determinant of A = -2.0

inversive of A :
 [[-2.   1.5]
 [ 1.  -0.5]]

 A @ A⁻¹ = I  
 [[1. 0.]
 [0. 1.]]


#Solve a System

Solve:

* 3x + 2y = 16
* 4x − y = 9

Tasks:

1. Write matrix A and vector b

2. Use np.linalg.solve

3. Verify by substitution

In [28]:
A= np.array([[3,4],[2,-1]])

b= np.array([16,9])

eq =np.linalg.solve(A,b)

print(f'x = {eq[0]}')
print(f'y = {eq[1]}')

print(f'3x + 2y = {3*eq[0] + 2*eq[1]}')
print(f'4x - y = {4*eq[0] - eq[1]}')

x = 4.7272727272727275
y = 0.4545454545454544
3x + 2y = 15.090909090909092
4x - y = 18.454545454545457


#Rank Investigation

In [30]:
M = np.array([[1, 2, 3],
              [2, 4, 6],
              [1, 0, 1]])

1. Compute rank

2. Are rows independent?

3. Explain the result

In [33]:
rank1= np.linalg.matrix_rank(M)
print(rank1)
print('rows are independent becuae rank = 2')

2
rows are independent
