#Exercise 1 – Array Creation

Create a NumPy array with values from 1 to 10.

Print:



*   Shape
*   Number of dimensions





In [2]:
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr.shape)
print(arr.ndim)


(2, 5)
2


#Exercise 2 – Matrix Creation

Create a 3 × 4 matrix filled with zeros.

Create a 2 × 5 matrix filled with ones.

Print their shapes.

In [3]:
arr1=np.zeros((3,4))
print(arr1.shape)
arr2=np.ones((2,5))
print(arr2.shape)

(3, 4)
(2, 5)


# Exercise 3 – Indexing & Slicing

Given:



```
arr = np.array([5, 10, 15, 20, 25])
```



* Print the first element.
* Print the last two elements.
* Modify the third element to 100.



In [10]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[0])
print(arr[3:5])
arr[2]=100
print(arr)

5
[20 25]
[  5  10 100  20  25]


#Exercise 4 – Element-wise Operations

Given:
```
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
```

* Add a and b

* Multiply a and b

* Square all elements of a

In [12]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("a + b =", a + b)

print("a * b =", a * b)

print("a ** 2 =", a ** 2)

a + b = [ 3  7 11]
a * b = [ 2 12 30]
a ** 2 = [ 4 16 36]


#Exercise 5 – Matrix Multiplication

Given:
```
A = np.array([[1, 2],
              [3, 4]])


B = np.array([[2, 0],
              [1, 2]])
```

* Compute element-wise multiplication.
* Compute matrix multiplication.
* Explain the difference in a comment.

In [17]:
A = np.array([[1, 2],
              [3, 4]])


B = np.array([[2, 0],
              [1, 2]])

element_wise= A * B

print(element_wise)

#element wise matches the input dimension exactly


matrix_multiplication= A @ B

print("")
print(matrix_multiplication)

#Matrix multiplication outer dimension of inputs

[[2 0]
 [3 8]]

[[ 4  4]
 [10  8]]


#Exercise 6 – Statistics Practice

Create a dataset of exam scores:

```
scores = np.array([
    [70, 80, 90],
    [85, 75, 95],
    [60, 65, 70],
    [90, 88, 92]
])

```

* Compute mean score per student.

* Compute mean score per subject.

* Find the highest and lowest score.

* Compute standard deviation.

In [20]:
scores = np.array([
    [70, 80, 90],
    [85, 75, 95],
    [60, 65, 70],
    [90, 88, 92]
])

print(np.mean(scores))
print(np.mean(scores,axis=1))
print(np.max(scores))
print(np.min(scores))
print(np.std(scores))

80.0
[80. 85. 65. 90.]
95
60
11.210114480533491
